name: Snyk Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install project dependencies (Maven Wrapper)
      run: |
        export JAVA_HOME=$JAVA_HOME_17_X64
        ./mvnw clean install -DskipTests

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Run Snyk to check for vulnerabilities
      run: |
        export JAVA_HOME=$JAVA_HOME_17_X64
        snyk test --maven
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
