name: Snyk Vulnerability Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn clean install -DskipTests
      
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/gradle-jdk17@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
