name: Snyk Maven Scan with Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk test and save JSON report
      continue-on-error: true
      run: |
        export JAVA_HOME=$JAVA_HOME_17_X64
        snyk test --maven \
          --project-name=java-snyk-github \
          --project-environment=backend \
          --json > snyk-report.json

    - name: Upload Snyk JSON report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: snyk-json-report
        path: snyk-report.json

    - name: Monitor project in Snyk UI
      run: |
        export JAVA_HOME=$JAVA_HOME_17_X64
        snyk monitor --maven \
          --project-name=java-snyk-github \
          --project-environment=backend 
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
